<?php

define ('_TESTPLUGIN_NEWACTU',         'Actu');
define ('_TESTPLUGIN_NEWACTU_DSC',     'test - les cernieres actu');

define ('_TESTPLUGIN_NEWANNONCE',       'Annonce');
define ('_TESTPLUGIN_NEWANNONCE_DSC',   'test - les dernieres annonces');

define ('_TESTPLUGIN_PASGLOP',          'Pas glop');
define ('_TESTPLUGIN_PASGLOP_DSC',      "test d'un plugin sur un module non valide");

define ('_TESTPLUGIN_SUBJECT',          'sujet');
define ('_TESTPLUGIN_DESCRIPTION',      'Description');
define ('_TESTPLUGIN_DATECREATION',     'Date de création');
define ('_TESTPLUGIN_DATEMODIFICATION', 'Date de modification');
define ('_TESTPLUGIN_LASTTANNNCES',     'Liste des dernieres annonces soumises');
define ('_TESTPLUGIN_ANNONCE',          'Annonce');
define ('_TESTPLUGIN_AUTHOR',           'Créer par JJD');

define ('_TESTPLUGIN_ANNONCENAME',      'test plugin annonces');
define ('_TESTPLUGIN_ANNONCEDSC',      'Plugin developpé pour test');

//define ('_TESTPLUGIN_',              '');

  
?>
