<?php

define ('_LEXIQUE_LEXIQUE',              'lexique');
define ('_LEXIQUE_DESCRIPTION',          'Description');
define ('_LEXIQUE_DATECREATION',         'date de création');
define ('_LEXIQUE_DATEMODIFICATION',     'Date de modification');
define ('_LEXIQUE_NEWENTRY',             'Nouvelles entrées dans les lexiques');
define ('_LEXIQUE_LASTTERMES',           'Derniers termes créés dans les lexiques');
define ('_LEXIQUE_TERME',                'Entrée');

define ('_LEXIQUE_NEWLEXIQUE',           'Nouveaux lexiques');
define ('_LEXIQUE_NEWLEXIQUE_DSC',       'Liste des derniers lexiques crées');
define ('_LEXIQUE_SHORTDEF',             'Déinition courte');
define ('_LEXIQUE_DEFNITION1',           'Déinition principale');

?>
