<?php

define ('_NEWBB_NAME',             'Forum');
//define ('_NEWBB_PLUGIN_DESC',      'Les Sujets populaires');

define ('_NEWBB_TIME',           'Date');
define ('_NEWBB_PLUGIN_DESC',    'Les sujets chaud du site');
define ('_NEWBB_HITS',           'Nombre de hits');

define ('_NEWBB_SOURCE',          'Source');
define ('_NEWBB_SOURCE_DSC',      'Permet de définir les messages les plus regarder, les plus discuter , ...');
define ('_NEWBB_SOURCE_LIST',     'derniers messages de tous les forums|'
                                 .'derniersmessages les plus regarder des 2 derniers mois|'
                                 .'derniersmessages les plus discuter des 2 derniers mois');

define ('_NEWBB_FORMAT_DATE',             'd-m-y');

?>
