<?php
// $Id: install.php 72 2005-11-12 05:09:33Z tuff $
define('_INTRO_TITLE', 'Syndicates this site');
define('_INTRO_CONTENT', '<a href="rss.php"><img src="images/rss.gif" alt="RSS feed" /></a> <a href="rss.php"> <img src="images/xml.gif" alt="RSS feed" /></a>

At {SITENAME} we provide our XML <a href="rss.php">RSS feed</a> that you can quickly find the latest updates and short descriptions with an RSS reader.

If you are unfamiliar with RSS, it is a <a href="http://blogs.law.harvard.edu/tech/rss">web standard</a> for publishing news headlines. You can read the RSS feed with special software and easily embed them into blogs and other web content.

For the RSS reader software, we recommend <a href="http://ranchero.com/netnewswire/#lite">NetNewsWire Lite</a> (Mac OS X), <a href="http://sourceforge.net/projects/feedreader">Feedreader</a> (Windows) and <a href="http://www.disobey.com/amphetadesk/">AmphetaDesk</a> (cross platform), or you may search for an <a href="http://www.google.com/search?ie=UTF-8&oe=UTF-8&q=RSS+reader">RSS reader</a> in Google.

Here are the URLs for each section\'s feed:
{SUB}
By the way, the RSS feed of this site is generated by <a href="http://www.brandycoke.com/products/rssfit/">RSSFit</a>.');
define('_INSTALL_INTRO_SUB', '<a href="{URL}">{TITLE}</a>: {DESC}<br /><a href="{URL}">{URL}</a><br /><br />');

?>