<?php
define ('_HERRSS_HEADER',               'Flux RSS ');
define ('_HERRSS_NAME_PHP5',            'Hermes RSS PHP5');
define ('_HERRSS_PLUGIN_PHP5_DESC',     'Gestion de flux RSS pour PHP5 (dom)');

define ('_HERRSS_NAME',                 'Hermes Flux RSS');
define ('_HERRSS_PLUGIN_DESC',          'Gestion de flux RSS');

define ('_HERRSS_SUBJECT',          'Sujet');


define ('_HERRSS_CATSIZE',     'Taille des titres');
define ('_HERRSS_CATSIZE_DESC',     'Taille de la police du nom de la catégorie en cas de regroupement (affichage=1) ex: +2 ');


define ('_HERRSS_MAXITEM',              'Nombre d\'article maximim');
define ('_HERRSS_MAXITEM_DSC',          '');

define ('_HERRSS_TITLE',                'Titre');
define ('_HERRSS_TITLE_DSC',            '');

define ('_HERRSS_AUTHOR',               'Auteur');
define ('_HERRSS_AUTHOR_DSC',           '');

define ('_HERRSS_DESCRIPTION',          'Description');
define ('_HERRSS_DESCRIPTION_DSC',      'Description');

define ('_HERRSS_LINK',                 'Lien');
define ('_HERRSS_LINK_DSC',             '');

define ('_HERRSS_GUID',                 'Guide');
define ('_HERRSS_GUID_DSC',             '');

define ('_HERRSS_PUBDATE',              'Publication');
define ('_HERRSS_PUBDATE_DSC',          '');


define ('_AD_HERRSS_AFFICHAGE_IMG',          "Image");
define ('_AD_HERRSS_AFFICHAGE_IMG_DSC',      "Mode d'affichage de l'image");
define ('_AD_HERRSS_AFFICHAGE_IMG_LIST_',    'Indépendante|Incrustée');

//---------------------------------------------------------

?>
