<?php

define ('_CATADS_NAME',             'Ads');
define ('_CATADS_PLUGIN_DESC',      'Latest ads');

define ('_CATADS_HEADER',           'Latest ads');
define ('_CATADS_CATEGORIE',        'Category');
define ('_CATADS_DESCRIPTION',      'Description');
define ('_CATADS_SUBJECT',          'Subjet');
define ('_CATADS_TITLE',            'Title');
define ('_CATADS_ANNONCES',         'Ads');
define ('_CATADS_ALL_ANNONCES',     'All the ads');
define ('_CATADS_DATEPUBLISHED',    'Date of publication');
define ('_CATADS_DATECREATION',     'Date of creation');
define ('_CATADS_DATEEXPIRATION',   'Date of expiration');
define ('_CATADS_ORDER_DESC',       'Enter the serial number of column (0=hide)');
define ('_CATADS_AUTHOR',           'Author');
define ('_CATADS_TOWN',             'City');
define ('_CATADS_AFFICHAGE_DESC',   '0 = Display by list <br>1 = Display by category');
define ('_CATADS_CATSIZE_DESC',     'Font size of the name of the category in the event of reunification (display=1) ex: +2 ');


define ('_CATADS_PRICE',         "Price");



//define ('_CATADS_TOWN',             'City');


define ('_CATADS_PERIODE',          'Period');
define ('_CATADS_PERIODE_DESC',     'Number of months of research in relation to the date of creation');

define ('_CATADS_MAXITEM',          'Period');
define ('_CATADS_MAXITEM_DESC',     "Maximum ads to insert");


//Chapter level of the table info returns
//0 = The lowest level for the content
//1 = Chapter 1
//2 = Chapter 1.2  According to the previous level  ect
define ('_CATADS_LEVEL',            'Level'); 


?>
