<?php

define ('_CATADS_NAME',             'Annonces');
define ('_CATADS_PLUGIN_DESC',      'Les dernières annonces du site');

define ('_CATADS_HEADER',           'Les dernières annonces du site');
define ('_CATADS_CATEGORIE',        'Catégorie');
define ('_CATADS_DESCRIPTION',      'Description');
define ('_CATADS_SUBJECT',          'Sujet');
define ('_CATADS_TITLE',            'Titre');
define ('_CATADS_ANNONCES',         'Annonces');
define ('_CATADS_ALL_ANNONCES',     'Toutes les annonces du site');
define ('_CATADS_DATEPUBLISHED',    'Date de publication');
define ('_CATADS_DATECREATION',     'Date de création');
define ('_CATADS_DATEEXPIRATION',   "Date d'expiration");
define ('_CATADS_ORDER_DESC',       "Indiquer le numéro d'ordre de la colonne (0=masquée)");
define ('_CATADS_AUTHOR',           'Auteur');
define ('_CATADS_TOWN',             'Ville');
define ('_CATADS_AFFICHAGE_DESC',   '0 = Affichage en liste <br>1 = Affichage regroupé par catégorie');

define ('_CATADS_IMGCATEGORIE_DESC', "Affichage de l'image de la catégorie, 0 = non, 1 = oui");
define ('_CATADS_IMGANNONCE_DESC',   "Affichage de l'image de l'annonce, 0 = non, 1 = oui");


define ('_CATADS_PRICE',         "Prix");

define ('_CATADS_MODE_AFFICHAGE',         "Mode d'affichage");
define ('_CATADS_IMGCATEGORIE',         "Image de la catégorie");
define ('_CATADS_IMGANNONCE',         "Image de l'annonce");

 

//define ('_CATADS_TOWN',             'Ville');


define ('_CATADS_AFFICHAGE_LIST',     "Affichage en liste|Affichage regroupé par catégorie");


//niveau de chapitre des infos du tableau retourné
//0 = niveau le plus bas pour le contenu
//1 = chapitre 1
//2 = chapitre 1.2  selon le niveau précédent  ect
define ('_CATADS_LEVEL',            'Niveau'); 



?>
