<?php

define ('_MYDOWNLOADS_NAME',               'Téléchargements');
define ('_MYDOWNLOADS_MODULE_DESCRIPTION', 'Ce plugin présentes les derniers télèchragement mis à disposition');
define ('_MYDOWNLOADS_HEADER',             'Les derniers téléchargements');
define ('_MYDOWNLOADS_ALL_DOWNLOAD',       'Tous les téléchargements');


define ('_MYDOWNLOADS_ID',          'Id');
define ('_MYDOWNLOADS_VERSION',     'Version');
define ('_MYDOWNLOADS_DESCRIPTION', 'Description');
define ('_MYDOWNLOADS_DATE',        'Date');
define ('_MYDOWNLOADS_TITLE',       'Titre');
define ('_MYDOWNLOADS_VOTES',       'votes');
define ('_MYDOWNLOADS_HOMEPAGE',    "Pade d'acueuil");
define ('_MYDOWNLOADS_FORMATDATE',        'd-m-Y');





?>
