<?php
// $Id: xoops_version.php 244 2006-07-20 08:41:42Z tuff $
###############################################################################
##                RSSFit - Extendable XML news feed generator                ##
##                Copyright (c) 2004 - 2006 NS Tai (aka tuff)                ##
##                       <http://www.brandycoke.com/>                        ##
###############################################################################
##                    XOOPS - PHP Content Management System                  ##
##                       Copyright (c) 2000 XOOPS.org                        ##
##                          <http://www.xoops.org/>                          ##
###############################################################################
##  This program is free software; you can redistribute it and/or modify     ##
##  it under the terms of the GNU General Public License as published by     ##
##  the Free Software Foundation; either version 2 of the License, or        ##
##  (at your option) any later version.                                      ##
##                                                                           ##
##  You may not change or alter any portion of this comment or credits       ##
##  of supporting developers from this source code or any supporting         ##
##  source code which is considered copyrighted (c) material of the          ##
##  original comment or credit authors.                                      ##
##                                                                           ##
##  This program is distributed in the hope that it will be useful,          ##
##  but WITHOUT ANY WARRANTY; without even the implied warranty of           ##
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            ##
##  GNU General Public License for more details.                             ##
##                                                                           ##
##  You should have received a copy of the GNU General Public License        ##
##  along with this program; if not, write to the Free Software              ##
##  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA ##
###############################################################################

if (!defined('XOOPS_ROOT_PATH')) {
	die("XOOPS root path not defined");
}

$modversion['name'] = _MI_RSSFIT_NAME;
$modversion['version'] = '1.22';
$modversion['description'] = _MI_RSSFIT_DESC;
$modversion['author'] = "NS Tai (aka tuff)";
$modversion['credits'] = "<a href='http://www.brandycoke.com/'>Brandycoke Productions</a>";
$modversion['help'] = "";
$modversion['license'] = "<a href='http://creativecommons.org/licenses/GPL/2.0/' target='_blank'>Human-Readable Commons Deed</a><br /><a href='http://www.gnu.org/copyleft/gpl.html' target='_blank'>Full Legal Code</a>";
$modversion['official'] = 0;
$modversion['image'] = "images/rssfit.png";
$modversion['dirname'] = "rss";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "rssfit_plugins";
$modversion['tables'][1] = "rssfit_misc";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Script to run on install/unstall/update
$modversion['onInstall'] = 'include/install.php';
$modversion['onUpdate'] = 'include/install.php';

// Menu -- content in main menu block
$modversion['hasMain'] = 1;

// Templates
$modversion['templates'][1]['file'] = 'rssfit_index.html';
$modversion['templates'][1]['description'] = _MI_TMPL_INTRO;
$modversion['templates'][2]['file'] = 'rssfit_rss.html';
$modversion['templates'][2]['description'] = _MI_TMPL_RSS;

//	Module Configs
// $xoopsModuleConfig['overall_entries']
$modversion['config'][1]['name'] = 'overall_entries';
$modversion['config'][1]['title'] = '_MI_OVERALL_ENTRIES';
$modversion['config'][1]['description'] = '_MI_OVERALL_ENTRIES_DESC';
$modversion['config'][1]['formtype'] = 'textbox';
$modversion['config'][1]['valuetype'] = 'int';
$modversion['config'][1]['default'] = 20;

// $xoopsModuleConfig['plugin_entries']
$modversion['config'][2]['name'] = 'plugin_entries';
$modversion['config'][2]['title'] = '_MI_PLUGIN_ENTRIES';
$modversion['config'][2]['description'] = '_MI_PLUGIN_ENTRIES_DESC';
$modversion['config'][2]['formtype'] = 'textbox';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = 5;

// $xoopsModuleConfig['sort']
$modversion['config'][3]['name'] = 'sort';
$modversion['config'][3]['title'] = '_MI_ENTRIES_SORT';
$modversion['config'][3]['description'] = '_MI_ENTRIES_SORT_DESC';
$modversion['config'][3]['formtype'] = 'select';
$modversion['config'][3]['valuetype'] = 'text';
$modversion['config'][3]['default'] = 'd';
$modversion['config'][3]['options'] = array(_MI_ENTRIES_SORT_DATE=>'d', _MI_ENTRIES_SORT_CAT=>'c');

// $xoopsModuleConfig['cache']
$modversion['config'][4]['name'] = 'cache';
$modversion['config'][4]['title'] = '_MI_CACHE';
$modversion['config'][4]['description'] = '_MI_CACHE_DESC';
$modversion['config'][4]['formtype'] = 'textbox';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = 0;

// $xoopsModuleConfig['max_char']
$modversion['config'][5]['name'] = 'max_char';
$modversion['config'][5]['title'] = '_MI_MAXCHAR';
$modversion['config'][5]['description'] = '_MI_MAXCHAR_DESC';
$modversion['config'][5]['formtype'] = 'textbox';
$modversion['config'][5]['valuetype'] = 'int';
$modversion['config'][5]['default'] = 0;

// $xoopsModuleConfig['strip_html']
$modversion['config'][6]['name'] = 'strip_html';
$modversion['config'][6]['title'] = '_MI_STRIPHTML';
$modversion['config'][6]['description'] = '_MI_STRIPHTML_DESC';
$modversion['config'][6]['formtype'] = 'yesno';
$modversion['config'][6]['valuetype'] = 'int';
$modversion['config'][6]['default'] = 0;

// $xoopsModuleConfig['utf8']
$modversion['config'][7]['name'] = 'utf8';
$modversion['config'][7]['title'] = '_MI_ENCODE_UTF8';
$modversion['config'][7]['description'] = '_MI_ENCODE_UTF8_DESC';
$modversion['config'][7]['formtype'] = 'yesno';
$modversion['config'][7]['valuetype'] = 'int';
$modversion['config'][7]['default'] = 0;

// $xoopsModuleConfig['mime']
$modversion['config'][8]['name'] = 'mime';
$modversion['config'][8]['title'] = '_MI_OUTOUT_MIME';
$modversion['config'][8]['description'] = '';
$modversion['config'][8]['formtype'] = 'select';
$modversion['config'][8]['valuetype'] = 'int';
$modversion['config'][8]['default'] = 1;
$modversion['config'][8]['options'] = array(_MI_OUTOUT_MIME_XML=>1, _MI_OUTOUT_MIME_HTML=>2, _MI_OUTOUT_MIME_PHP=>3);

?>