<?php

define ('_NEWS_NAME',             'News');
define ('_NEWS_MODULE_DSC',       'Les dernières nouvelles du site');
define ('_NEWS_HEADER',           'Les derniers articles du site');
define ('_NEWS_CATEGORIE',        'Catégorie');
define ('_NEWS_DESCRIPTION',      'Description');
define ('_NEWS_SUBJECT',          'Sujet');
define ('_NEWS_TITLE',            'Titre');
define ('_NEWS_NEWS',             'Nouvelles');
define ('_NEWS_ALL_NEWS',         'Toutes les nouvelles du site');
define ('_NEWS_DATEPUBLISHED',    'Date de publication');
define ('_NEWS_AUTHOR',           'Auteur');

define ('_NEWS_AFFICHAGE_LIST',   "Affichage en liste|Affichage regroupé par catégorie");
define ('_NEWS_AFFICHAGE_DESC',   '0 = Affichage en liste <br>1 = Affichage regroupé par catégorie');


?>
