<?php


define ('_SMARTS_NAME',             'SmartSection');
define ('_SMARTS_PLUGIN_DESC',      'Les derniers articles site');

//define ('_SMARTS_CATNAME',          'SmartSectionCat');
define ('_SMARTS_CATNAME_DESC',     'Affiche les article défini pour chaque catégorie');

define ('_SMARTS_HEADER',           'Les derniers articles du site');
define ('_SMARTS_CATEGORIE',        'Catégorie');
define ('_SMARTS_SUMMARY',          'Sommaire');

define ('_SMARTS_DESCRIPTION',      'Description');
define ('_SMARTS_SUBJECT',          'Sujet');
define ('_SMARTS_TITLE',            'Titre');
define ('_SMARTS_ARTICLES',         'Articles');
define ('_SMARTS_ALL_ARTICLES',     'Tous les articles');




define ('_SMARTS_LECTURES',     "Nombre de lectures");
define ('_SMARTS_CAT_LECTURES',     "Nombre de lectures dans la catégorie");

define ('_SMARTS_PUBLISHED',     "Date de publication");
define ('_SMARTS_LECTURE',     "Lecture");
define ('_SMARTS_CATNAME',     "Catégorie");
define ('_SMARTS_CATLECTURE',     "Visite");
define ('_SMARTS_CATCREATED',     "Date de création");



define ('_SMARTS_SHOWTITLE_DESC',     "Affichage des titres");
define ('_SMARTS_SHOWCATEGORIE_DESC',     "Affichage des catégories");
define ('_SMARTS_ARTICLESLISTE_DESC',     "Liste des articles de cette catégorie.");
define ('_SMARTS_READNEXT',               'Lire la suite....');

define ('_SMARTS_AFFICHAGE_LIST',     "Affichage en liste|Affichage regroupé par catégorie");
define ('_SMARTS_AFFICHAGE_DESC',   '0 = Affichage en liste <br>1 = Affichage regroupé par catégorie');

?>
