<?php

define ('_POLLS_NAME',           'Sondages');
define ('_POLLS_MODULE_DESCRIPTION',    'Ce plugin recupères les derniers derniers sondages du site');
define ('_POLLS_HEADER',         'Les derniers sondages du site');
define ('_NEWS_ALL_POLLS',         'Tous les sondages');



define ('_POLLS_ID',          'Id');
define ('_POLLS_QUESTION',    'Question');
define ('_POLLS_DESCRIPTION', 'Description');
define ('_POLLS_STARTTIME',   'Début');
define ('_POLLS_ENDTIME',     'echéance');
define ('_POLLS_VOTES',       'votes');

define ('_POLLS_DATE',       'd-m-Y');





?>
