<?php

define ('_POLLS_NAME',        'Sondages');
define ('_POLLS_MODULE_DSC',  'Ce plugin recupères les derniers derniers sondages du site');
define ('_POLLS_HEADER',      'Les derniers sondages du site');
define ('_NEWS_ALL_POLLS',    'Tous les sondages');



define ('_POLLS_ID',          'Id');
define ('_POLLS_QUESTION',    'Question');
define ('_POLLS_DESCRIPTION', 'Description');
define ('_POLLS_STARTTIME',   'Début');
define ('_POLLS_ENDTIME',     'echéance');
define ('_POLLS_VOTES',       'votes');

define ('_POLLS_DATE',       'd-m-Y');
define ('_POLLS_AUCUN.',       'Aucun');
define ('_POLLS_DERNIERSS',       'derniers');



?>
