<?php


define ('_WLINKS_NAME',             'WebLink');
define ('_WLINKS_PLUGIN_DESC',      'Les derniers articles site');
define ('_WLINKS_ALL_LINKS',      'Tous les liense');
define ('_WLINKS_HEADER',           'Les derniers liens du site');
define ('_WLINKS_TITLE',            'Titre');
define ('_WLINKS_CATEGORIE',        'Catégorie');
define ('_WLINKS_SUMMARY',          'Sommaire');

define ('_WLINKS_DESCRIPTION',      'Description');
define ('_WLINKS_SUBJECT',          'Sujet');


define ('_WLINKS_CATCREATED',     "Date de création");
define ('_WLINKS_CATNAME',     "Catégorie");
define ('_WLINKS_PUBLISHED',     "Date de publication");
define ('_WLINKS_SHOWTITLE_DESC',     "Affichage des titres");
define ('_WLINKS_SHOWCATEGORIE_DESC',     "Affichage des catégories");






define ('_WLINKS_AFFICHAGE_LIST',     "Affichage en liste|Affichage regroupé par catégorie");
define ('_WLINKS_AFFICHAGE_DESC',   '0 = Affichage en liste <br>1 = Affichage regroupé par catégorie');

define ('_WLINKS_LECTURE',     "Lecture");
define ('_WLINKS_CATLECTURE',     "Visite");




?>
