<?php

define ('_CATADS_NAME',             'Annonces');
define ('_CATADS_PLUGIN_DESC',      'Les dernieres annonces du site');

define ('_CATADS_HEADER',           'Les dernieres annonces du site');
define ('_CATADS_CATEGORIE',        'Catégorie');
define ('_CATADS_DESCRIPTION',      'Description');
define ('_CATADS_SUBJECT',          'Sujet');
define ('_CATADS_TITLE',            'Titre');
define ('_CATADS_ANNONCES',         'Annonces');
define ('_CATADS_ALL_ANNONCES',     'Toutes les annonces du site');
define ('_CATADS_DATEPUBLISHED',    'Date de publication');
define ('_CATADS_DATECREATION',     'Date de création');
define ('_CATADS_DATEEXPIRATION',   "Date d'expiration");
define ('_CATADS_ORDER_DESC',       "Indiquer le numéro d'ordre pde la colonne (0=masquée)");
define ('_CATADS_AUTHOR',           'Auteur');
define ('_CATADS_TOWN',             'Ville');
define ('_CATADS_AFFICHAGE_DESC',   '0 = Affichage en liste <br>1 = Affichage regroupé par catégorie');
define ('_CATADS_CATSIZE_DESC',     'Taille de la police du nom de la catégorie en cas de regroupement (affichage=1) ex: +2 ');

//define ('_CATADS_TOWN',             'Ville');


define ('_CATADS_PERIODE',          'Période');
define ('_CATADS_PERIODE_DESC',     'Nombre de mois de recherche par rapport à la date de création');

define ('_CATADS_MAXITEM',          'Période');
define ('_CATADS_MAXITEM_DESC',     "Nombre d'annonce maximum à insérer");


//niveau de chapitre des info du tableau retourne
//0 = niveau le plus bas pour le contenu
//1 = chapitre 1
//2 = chapitre 1.2  selon le niveau précédent  ect
define ('_CATADS_LEVEL',            'Niveau'); 


?>
